### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by itsbenter** [itsbenter/QuipsAndQuestions#1]
# Release
## Regular Questions
Appear on non festival days. May have conditions before appearing. Aim for 3 questions per character.
- [ ] Alex
- [ ] Elliot
- [ ] Harvey
- [ ] Sam
- [ ] Sebastian
- [ ] Shane
- [ ] Abigail
- [ ] Emily
- [ ] Haley
- [ ] Leah
- [ ] Maru
- [ ] Penny
- [ ] Caroline
- [ ] Clint
- [ ] Demetrius
- [ ] Dwarf
- [ ] Evelyn
- [ ] George
- [ ] Gus
- [ ] Jas
- [ ] Jodi
- [ ] Kent
- [ ] Krobus
- [ ] Leo
- [ ] Lewis
- [ ] Linus
- [ ] Marnie
- [ ] Pam
- [ ] Pierre
- [ ] Robin
- [ ] Sandy
- [ ] Vincent
- [ ] Willy
- [ ] Wizard

## Festival Questions
Only appears during respective festival.
- [ ] Egg Festival
- [ ] Flower Dance
- [ ] Luau
- [ ] Dance of the Moonlight Jellies
- [ ] Spirit's Eve
- [ ] Stardew Valley Fair
- [ ] Night Market
- [ ] Ice Festival
- [ ] Feast of Winter Star
